### ISSUE TITLE
Pull all Polish Radio Channels from https://www.radio.pervii.com/.

### ISSUE THREAD

**Issue by Skates1616** [junguler/m3u-radio-music-playlists#3]
Would it be possible to pull all Polish radio channels from https://www.radio.pervii.com/?

Right now, the list is really limited in comparison to the list on:

https://radio.pervii.com/en/1/Polish.htm

And thank you again for setting up these scrapers!

**Comment by junguler** [comment]
hi, i've looked into the page you linked and altho there are 167 stations listed in the page only 19 of them are online and active at the moment, other stations are dead or inactive as evident by the error sign underneath them, you can't listen to them because nothing is being broadcasted, the website just haven't removed them for whatever reason

![screenshot](https://user-images.githubusercontent.com/59083599/183747569-d1bef077-3ffe-4d0c-8820-907c6368a730.jpg)

the way my repo works is i download the streams from this [page](https://www.radio.pervii.com/en/online-playlists-m3u.htm) which automatically grabs 100 or less popular stations from each category in order of popularity and inserts them into a m3u file, those active streams are already in the file in my repo and if the number increase or decreases it's going to be shown here every time i push updates

now it's possible to have more than 100 streams in a certain category if i scrape the pages manually but in the case of what you want it would be dead links that don't work and are useless unfortunately

having said that i highly doubt there is only 19 polish radio streams online, it's just the case that this website only has this many of them that are active

**Comment by junguler** [comment]
hello again, i'm going to close this issue since there has been 3 days of inactivity on it, feel free to open this again if you have anything else to add or open a completely new issue
