### ISSUE TITLE
Add support for MyRadioOnline suite of websites

### ISSUE THREAD

**Issue by tepiloxtl** [junguler/m3u-radio-music-playlists#35]
There is a whole suite of websites under MyRadioOnline umbrella (MyOnlineRadio.de UKRadioLive.com MyRadioOnline.es MyRadioOnline.it MyOnlineRadio.at MyOnlineRadio.sk MyOnlineRadio.hu MyRadioEnDirect.fr MyOnlineRadio.nl IrishRadioLive.com MyRadioEnVivo.mx MyRadioOnline.ro MyRadioOnline.cl MyRadioEnVivo.ar). Notably, MyRadioOnline.net is NOT a part of the same network, though it seems to emulate the same look of other sites.

While many websites exists, data from all supported countries can be scraped from a single one, no matter which one. You'll probably want to look into /get-radio-list endpoint to see how it works.

I'm making my own scraper for the website in python. I don't know much about posix shell, but I can help with website itself

**Comment by junguler** [comment]
hello, i've aware of those websites, i wanted to scrape them but the issue is there is no genre specified for them, there are just a bunch of radio streams listed there in no order other than just popularity

as for the https://myradioonline.net/ it looks promising altho there is just a handful of genres to scrape from and overall there aren't that many radio streams listed, 7 pages of 20-30 streams per page, i'm not against the idea of adding this website however and will add it to the list

the next website i'll be scraping is already decided but i was busy updating the +checked+ folder this past few weeks so be on the lookout for that whenever it finally arrives

**Comment by junguler** [comment]
i'm going to convert this issue to a discussion, feel free to keep the conversation going if you want
